name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '24 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl "https://www.pizzaexpress.com/api/Restaurants/FindRestaurantsByLatLong?latitude=51.50354&longitude=-0.127695&pageNumber=1&limit=1000" > pe-locations.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
